sensors:
  - sensor: livox
    topics_sensor: ['/livox/imu', '/livox/lidar']
    msgs_types: ['sensor_msgs/Imu', 'sensor_msgs/PointCloud2']
    topics_frequecy: [200, 10]
    fequency_tolerance: [0.1, 0.1]
    max_downtime: 1
    status_topic_pub: '/status/livox'
  - sensor: xsens
    topics_sensor: ['/imu/data', '/imu/mag']
    msgs_types: ['sensor_msgs/Imu', 'sensor_msgs/MagneticField']
    topics_frequecy: [400, 100]
    fequency_tolerance: [0.1, 0.1]
    max_downtime: 1
    status_topic_pub: '/status/xsens'
  - sensor: realsense
    topics_sensor: ['/d455i/accel/imu_info', '/d435i/align_to_color/parameter_descriptions', '/d455i/align_to_color/parameter_updates', '/d455i/aligned_depth_to_color/camera_info', '/d455i/aligned_depth_to_color/image_raw', '/d455i/color/camera_info', '/d455i/color/image_raw', '/d455i/gyro/imu_info', '/d455i/imu']
    msgs_types: ['realsense2_camera/IMUInfo', 'dynamic_reconfigure/ConfigDescription', 'dynamic_reconfigure/Config', sensor_msgs/CameraInfo, sensor_msgs/Image, sensor_msgs/CameraInfo, sensor_msgs/Image,'realsense2_camera/IMUInfo', 'sensor_msgs/Imu']
    topics_frequecy: [30,30,30,30,30,30,30,30,30]
    fequency_tolerance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    max_downtime: 1
    status_topic_pub: '/status/realsense'
